Mfu mbu dev
sparse-generative-ai/open-moe-llm-leaderboard pull request #1
Opened 2024-05-12 11:45 UTC by SecretSettler

2024-05-13 01:35 UTC, future-xy commented on src/backend/hflm_with_measurement.py
> +                d_ff = d_model + model_config.ff_ratio
"ff_ratio"是加上去的吗？确认下

2024-05-13 01:35 UTC, future-xy commented on src/backend/hflm_with_measurement.py
> +        ffn_params = n_layers * d_ff * 2 * d_model
这个常数“2”代表什么？

2024-05-13 01:35 UTC, future-xy commented on src/backend/hflm_with_measurement.py
> +        flops_per_token = 2 * model_size + 2 * n_layers * context_length * d_model + 4 * d_model + 2 * d_model * n_vocab
“2 * d_model * n_vocab"，这里是不是不太对，一个token不会激活整个embedding吧？

2024-05-13 01:35 UTC, future-xy commented on src/backend/hflm_with_measurement.py
> +        kv_size = (output_length - 1) * per_token_kv_size / 2e9
单位有一点混乱，为什么有的地方“* 1e9“，有的是"/1e9" 或者 “/2e9”？

2024-05-13 01:35 UTC, future-xy commented on src/backend/hflm_with_measurement.py
> +        achieve_mem_bw = (model_size * precision_bytes / 1e9 + kv_size) * token_per_sec
这里的“kv_size”是最后一轮decoding时用到的kv cache size，但是token_per_sec是整个decoding过程的平均token per second。不能一起计算，会导致算出来的bw偏大。

2024-05-13 01:35 UTC, future-xy commented on src/backend/hflm_with_measurement.py
> +        flops_per_token = 2 * model_size + 2 * n_layers * context_length * d_model + 4 * d_model + 2 * d_model * n_vocab
同理，这里算的flops per token是最后一个token对应的flops，因为context length用的是最终的context length，忽略了decoding过程中context逐渐增长的特性。导致算出来的mfu偏高。

2024-05-13 11:50 UTC, SecretSettler commented on src/backend/hflm_with_measurement.py
> +        ffn_params = n_layers * d_ff * 2 * d_model
每个fp包含两个flops, 乘和加

2024-05-13 11:51 UTC, SecretSettler commented on src/backend/hflm_with_measurement.py
> +        kv_size = (output_length - 1) * per_token_kv_size / 2e9
我的问题，2是等差数列求和的分母，我图方便就一起写上去了，我改一下

2024-05-13 11:51 UTC, SecretSettler commented on src/backend/hflm_with_measurement.py
> +        achieve_mem_bw = (model_size * precision_bytes / 1e9 + kv_size) * token_per_sec
这个应该没问题

2024-05-13 11:51 UTC, SecretSettler commented on src/backend/hflm_with_measurement.py
> +        flops_per_token = 2 * model_size + 2 * n_layers * context_length * d_model + 4 * d_model + 2 * d_model * n_vocab
嗯，我改了一下，等下push上来

2024-05-13 11:52 UTC, SecretSettler commented on src/backend/hflm_with_measurement.py
> +                d_ff = d_model + model_config.ff_ratio
typo，乘上去的，已经改了

2024-05-13 12:15 UTC, SecretSettler commented on src/backend/hflm_with_measurement.py
> +        ffn_params = n_layers * d_ff * 2 * d_model
Transformer每个FFN有两个linear transformations

2024-05-14 14:15 UTC, future-xy requested changes

2024-05-14 14:15 UTC, future-xy commented on src/backend/hflm_with_measurement.py
> +        ffn_params = n_layers * d_ff * 2 * d_model
这里可能有问题，你再仔细看下，llama和opt都不一样

2024-05-14 14:15 UTC, future-xy commented on src/backend/hflm_with_measurement.py
> +        achieve_mem_bw = (model_size * precision_bytes / 1e9 + kv_size) * token_per_sec
假如output length=1，现在公式算出来会是什么结果？再仔细想想

2024-05-14 19:43 UTC, SecretSettler commented on src/backend/hflm_with_measurement.py
> +        achieve_mem_bw = (model_size * precision_bytes / 1e9 + kv_size) * token_per_sec
改好了，加了context prefilling 的size进去

2024-05-14 19:43 UTC, SecretSettler commented on src/backend/hflm_with_measurement.py
> +        ffn_params = n_layers * d_ff * 2 * d_model
我手动从模型中retrieve linear transformation的个数

2024-05-15 15:39 UTC, future-xy commented on src/backend/hflm_with_measurement.py
> +        kv_size = (2 * context_prefill_size + output_length - 1) * per_token_kv_size / 2
我看着没啥问题了，就是放里面*2再/2有点奇怪，写在括号外面回不回更清楚点？

2024-05-15 15:39 UTC, future-xy commented on src/backend/hflm_with_measurement.py
> +        for name, module in self.model.named_modules():
能否写一个单测，把主流几种模型都跑一下，和ground truth对一下？以防有corner case没有考虑到？

2024-05-16 10:25 UTC, merged